## Create random number tensor

In [1]:
import torch

In [2]:
x = torch.rand(5, 3)
print(x)
print(x[1,1])

tensor([[0.2568, 0.8963, 0.5467],
        [0.3213, 0.6231, 0.3522],
        [0.2862, 0.3822, 0.4310],
        [0.4779, 0.0072, 0.8374],
        [0.3526, 0.9407, 0.7372]])
tensor(0.6231)


## Reshape the tensor

In [5]:
x = torch.rand(4,4)
y = x.view(-1,8) # -1 means the size is inferred from other dimensions, here 8
print(y)

tensor([[0.9566, 0.4465, 0.2288, 0.6954, 0.6496, 0.6145, 0.7492, 0.1927],
        [0.0974, 0.2249, 0.4028, 0.7429, 0.3074, 0.6719, 0.8175, 0.4792]])


## Tensor to numpy

In [17]:
import numpy as np

a = torch.ones(5)
print(a)

b = a.numpy()
print(f"{b} data type = {type(b)}")

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.] data type = <class 'numpy.ndarray'>


In [19]:
# As the b is numpy version of a and if we made any inplace change ie when we make change to same memory
# location then the a will also be changed
print(f"Before change a = {a}")
a[2] = a[2]+1
print(f"After change a = {a}")

Before change a = tensor([1., 1., 2., 1., 1.])
After change a = tensor([1., 1., 3., 1., 1.])
